# Generated by Django 4.1.5 on 2023-02-16 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id_bus', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('marca', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_hora', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Paradero',
            fields=[
                ('id_paradero', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.DecimalField(decimal_places=4, max_digits=15)),
                ('longitud', models.DecimalField(decimal_places=4, max_digits=15)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiene', to='app.bus')),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiene', to='app.horario')),
                ('paradero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genera', to='app.paradero')),
            ],
        ),
    ]
